version: 2
updates:
  - package-ecosystem: npm
    directory: "/cactus-wealth-frontend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/cactus-wealth-backend"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
