"""add_missing_user_columns

Revision ID: 3c9dd9582201
Revises: add_cactus_module_tables
Create Date: 2025-08-04 02:12:04.341372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3c9dd9582201'
down_revision: Union[str, None] = 'add_cactus_module_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_tokens_expires_at', 'email_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_tokens_token'), 'email_tokens', ['token'], unique=True)
    op.create_index('ix_email_tokens_user_id', 'email_tokens', ['user_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('aaguid', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('backup_eligible', sa.Boolean(), nullable=False),
    sa.Column('backup_state', sa.Boolean(), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_index('ix_webauthn_credentials_created_at', 'webauthn_credentials', ['created_at'], unique=False)
    op.create_index('ix_webauthn_credentials_credential_id', 'webauthn_credentials', ['credential_id'], unique=False)
    op.create_index('ix_webauthn_credentials_last_used_at', 'webauthn_credentials', ['last_used_at'], unique=False)
    op.create_index('ix_webauthn_credentials_user_id', 'webauthn_credentials', ['user_id'], unique=False)
    op.add_column('cactus_content_matrix', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    op.add_column('cactus_content_matrix', sa.Column('content_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('cactus_content_matrix', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('cactus_content_matrix', sa.Column('publish_date', sa.DateTime(), nullable=True))
    op.alter_column('cactus_content_matrix', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_cactus_content_matrix_category'), table_name='cactus_content_matrix')
    op.drop_index(op.f('ix_cactus_content_matrix_created_at'), table_name='cactus_content_matrix')
    op.drop_index(op.f('ix_cactus_content_matrix_created_by'), table_name='cactus_content_matrix')
    op.drop_index(op.f('ix_cactus_content_matrix_title'), table_name='cactus_content_matrix')
    op.drop_index(op.f('ix_cactus_content_matrix_updated_at'), table_name='cactus_content_matrix')
    op.create_index('ix_cactus_content_category', 'cactus_content_matrix', ['category'], unique=False)
    op.create_index('ix_cactus_content_created_by', 'cactus_content_matrix', ['created_by'], unique=False)
    op.create_index('ix_cactus_content_publish_date', 'cactus_content_matrix', ['publish_date'], unique=False)
    op.create_index('ix_cactus_content_published', 'cactus_content_matrix', ['is_published'], unique=False)
    op.drop_column('cactus_content_matrix', 'content_brief')
    op.drop_column('cactus_content_matrix', 'estimated_duration')
    op.add_column('cactus_external_links', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('cactus_external_links', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True))
    op.add_column('cactus_external_links', sa.Column('required_role', sa.Enum('GOD', 'ADMIN', 'MANAGER', 'ADVISOR', 'SENIOR_ADVISOR', 'JUNIOR_ADVISOR', name='userrole'), nullable=True))
    op.drop_index(op.f('ix_cactus_external_links_category'), table_name='cactus_external_links')
    op.drop_index(op.f('ix_cactus_external_links_category_order'), table_name='cactus_external_links')
    op.drop_index(op.f('ix_cactus_external_links_created_at'), table_name='cactus_external_links')
    op.drop_index(op.f('ix_cactus_external_links_created_by'), table_name='cactus_external_links')
    op.drop_index(op.f('ix_cactus_external_links_is_active'), table_name='cactus_external_links')
    op.drop_index(op.f('ix_cactus_external_links_order_index'), table_name='cactus_external_links')
    op.drop_index(op.f('ix_cactus_external_links_title'), table_name='cactus_external_links')
    op.drop_index(op.f('ix_cactus_external_links_updated_at'), table_name='cactus_external_links')
    op.create_index('ix_cactus_links_active', 'cactus_external_links', ['is_active'], unique=False)
    op.create_index('ix_cactus_links_created_by', 'cactus_external_links', ['created_by'], unique=False)
    op.create_index('ix_cactus_links_order', 'cactus_external_links', ['order_index'], unique=False)
    op.create_index('ix_cactus_links_role', 'cactus_external_links', ['required_role'], unique=False)
    op.drop_column('cactus_external_links', 'title')
    op.drop_column('cactus_external_links', 'category')
    op.add_column('cactus_ideas', sa.Column('estimated_hours', sa.Integer(), nullable=True))
    op.add_column('cactus_ideas', sa.Column('assigned_to', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.alter_column('cactus_ideas', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('cactus_ideas', 'due_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_cactus_ideas_status_priority'), table_name='cactus_ideas')
    op.drop_index(op.f('ix_cactus_ideas_title'), table_name='cactus_ideas')
    op.drop_index(op.f('ix_cactus_ideas_updated_at'), table_name='cactus_ideas')
    op.add_column('cactus_library', sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('cactus_library', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('cactus_library', sa.Column('is_recommended', sa.Boolean(), nullable=False))
    op.add_column('cactus_library', sa.Column('completion_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('cactus_library', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('cactus_library', sa.Column('added_by', sa.Integer(), nullable=False))
    op.alter_column('cactus_library', 'content_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_cactus_library_author'), table_name='cactus_library')
    op.drop_index(op.f('ix_cactus_library_content_type'), table_name='cactus_library')
    op.drop_index(op.f('ix_cactus_library_content_type_rating'), table_name='cactus_library')
    op.drop_index(op.f('ix_cactus_library_created_at'), table_name='cactus_library')
    op.drop_index(op.f('ix_cactus_library_created_by'), table_name='cactus_library')
    op.drop_index(op.f('ix_cactus_library_is_completed'), table_name='cactus_library')
    op.drop_index(op.f('ix_cactus_library_title'), table_name='cactus_library')
    op.drop_index(op.f('ix_cactus_library_updated_at'), table_name='cactus_library')
    op.create_index('ix_cactus_library_added_by', 'cactus_library', ['added_by'], unique=False)
    op.create_index('ix_cactus_library_completion', 'cactus_library', ['completion_status'], unique=False)
    op.create_index('ix_cactus_library_recommended', 'cactus_library', ['is_recommended'], unique=False)
    op.create_index('ix_cactus_library_type', 'cactus_library', ['content_type'], unique=False)
    op.drop_constraint(op.f('cactus_library_created_by_fkey'), 'cactus_library', type_='foreignkey')
    op.create_foreign_key(None, 'cactus_library', 'users', ['added_by'], ['id'])
    op.drop_column('cactus_library', 'created_by')
    op.drop_column('cactus_library', 'is_completed')
    op.add_column('cactus_secure_credentials', sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('cactus_secure_credentials', sa.Column('required_role', sa.Enum('GOD', 'ADMIN', 'MANAGER', 'ADVISOR', 'SENIOR_ADVISOR', 'JUNIOR_ADVISOR', name='userrole'), nullable=False))
    op.add_column('cactus_secure_credentials', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('cactus_secure_credentials', sa.Column('last_accessed', sa.DateTime(), nullable=True))
    op.add_column('cactus_secure_credentials', sa.Column('access_count', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('cactus_secure_credentials_aws_secret_name_key'), 'cactus_secure_credentials', type_='unique')
    op.drop_index(op.f('ix_cactus_secure_credentials_aws_secret_name'), table_name='cactus_secure_credentials')
    op.drop_index(op.f('ix_cactus_secure_credentials_created_at'), table_name='cactus_secure_credentials')
    op.drop_index(op.f('ix_cactus_secure_credentials_created_by'), table_name='cactus_secure_credentials')
    op.drop_index(op.f('ix_cactus_secure_credentials_name'), table_name='cactus_secure_credentials')
    op.drop_index(op.f('ix_cactus_secure_credentials_service_type'), table_name='cactus_secure_credentials')
    op.drop_index(op.f('ix_cactus_secure_credentials_updated_at'), table_name='cactus_secure_credentials')
    op.create_index('ix_cactus_credentials_active', 'cactus_secure_credentials', ['is_active'], unique=False)
    op.create_index('ix_cactus_credentials_created_by', 'cactus_secure_credentials', ['created_by'], unique=False)
    op.create_index('ix_cactus_credentials_role', 'cactus_secure_credentials', ['required_role'], unique=False)
    op.create_index('ix_cactus_credentials_service', 'cactus_secure_credentials', ['service_name'], unique=False)
    op.drop_column('cactus_secure_credentials', 'service_type')
    op.add_column('cactus_video_slots', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('cactus_video_slots', sa.Column('script', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('cactus_video_slots', sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('cactus_video_slots', sa.Column('views_count', sa.Integer(), nullable=True))
    op.add_column('cactus_video_slots', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('cactus_video_slots', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.alter_column('cactus_video_slots', 'platform',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_cactus_video_slots_created_at'), table_name='cactus_video_slots')
    op.drop_index(op.f('ix_cactus_video_slots_created_by'), table_name='cactus_video_slots')
    op.drop_index(op.f('ix_cactus_video_slots_is_published'), table_name='cactus_video_slots')
    op.drop_index(op.f('ix_cactus_video_slots_platform'), table_name='cactus_video_slots')
    op.drop_index(op.f('ix_cactus_video_slots_platform_date'), table_name='cactus_video_slots')
    op.drop_index(op.f('ix_cactus_video_slots_scheduled_date'), table_name='cactus_video_slots')
    op.drop_index(op.f('ix_cactus_video_slots_title'), table_name='cactus_video_slots')
    op.drop_index(op.f('ix_cactus_video_slots_updated_at'), table_name='cactus_video_slots')
    op.create_index('ix_cactus_video_created_by', 'cactus_video_slots', ['created_by'], unique=False)
    op.create_index('ix_cactus_video_platform', 'cactus_video_slots', ['platform'], unique=False)
    op.create_index('ix_cactus_video_published', 'cactus_video_slots', ['is_published'], unique=False)
    op.create_index('ix_cactus_video_scheduled_date', 'cactus_video_slots', ['scheduled_date'], unique=False)
    op.drop_column('cactus_video_slots', 'duration')
    op.drop_column('cactus_video_slots', 'script_notes')
    op.add_column('users', sa.Column('manager_id', sa.Integer(), nullable=True))
    # Add email_verified safely: Postgres requires backfill for NOT NULL
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
        op.execute("UPDATE users SET email_verified = FALSE WHERE email_verified IS NULL")
        op.alter_column('users', 'email_verified', nullable=False)
    else:
        # SQLite path (used rarely for migrations): add nullable or skip
        op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('ix_users_manager_id', 'users', ['manager_id'], unique=False)
    op.create_index('ix_users_manager_role', 'users', ['manager_id', 'role'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index('ix_users_manager_role', table_name='users')
    op.drop_index('ix_users_manager_id', table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'manager_id')
    op.add_column('cactus_video_slots', sa.Column('script_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cactus_video_slots', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('ix_cactus_video_scheduled_date', table_name='cactus_video_slots')
    op.drop_index('ix_cactus_video_published', table_name='cactus_video_slots')
    op.drop_index('ix_cactus_video_platform', table_name='cactus_video_slots')
    op.drop_index('ix_cactus_video_created_by', table_name='cactus_video_slots')
    op.create_index(op.f('ix_cactus_video_slots_updated_at'), 'cactus_video_slots', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cactus_video_slots_title'), 'cactus_video_slots', ['title'], unique=False)
    op.create_index(op.f('ix_cactus_video_slots_scheduled_date'), 'cactus_video_slots', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_cactus_video_slots_platform_date'), 'cactus_video_slots', ['platform', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_cactus_video_slots_platform'), 'cactus_video_slots', ['platform'], unique=False)
    op.create_index(op.f('ix_cactus_video_slots_is_published'), 'cactus_video_slots', ['is_published'], unique=False)
    op.create_index(op.f('ix_cactus_video_slots_created_by'), 'cactus_video_slots', ['created_by'], unique=False)
    op.create_index(op.f('ix_cactus_video_slots_created_at'), 'cactus_video_slots', ['created_at'], unique=False)
    op.alter_column('cactus_video_slots', 'platform',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('cactus_video_slots', 'comments_count')
    op.drop_column('cactus_video_slots', 'likes_count')
    op.drop_column('cactus_video_slots', 'views_count')
    op.drop_column('cactus_video_slots', 'video_url')
    op.drop_column('cactus_video_slots', 'script')
    op.drop_column('cactus_video_slots', 'duration_minutes')
    op.add_column('cactus_secure_credentials', sa.Column('service_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_cactus_credentials_service', table_name='cactus_secure_credentials')
    op.drop_index('ix_cactus_credentials_role', table_name='cactus_secure_credentials')
    op.drop_index('ix_cactus_credentials_created_by', table_name='cactus_secure_credentials')
    op.drop_index('ix_cactus_credentials_active', table_name='cactus_secure_credentials')
    op.create_index(op.f('ix_cactus_secure_credentials_updated_at'), 'cactus_secure_credentials', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cactus_secure_credentials_service_type'), 'cactus_secure_credentials', ['service_type'], unique=False)
    op.create_index(op.f('ix_cactus_secure_credentials_name'), 'cactus_secure_credentials', ['name'], unique=False)
    op.create_index(op.f('ix_cactus_secure_credentials_created_by'), 'cactus_secure_credentials', ['created_by'], unique=False)
    op.create_index(op.f('ix_cactus_secure_credentials_created_at'), 'cactus_secure_credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_cactus_secure_credentials_aws_secret_name'), 'cactus_secure_credentials', ['aws_secret_name'], unique=False)
    op.create_unique_constraint(op.f('cactus_secure_credentials_aws_secret_name_key'), 'cactus_secure_credentials', ['aws_secret_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('cactus_secure_credentials', 'access_count')
    op.drop_column('cactus_secure_credentials', 'last_accessed')
    op.drop_column('cactus_secure_credentials', 'is_active')
    op.drop_column('cactus_secure_credentials', 'required_role')
    op.drop_column('cactus_secure_credentials', 'service_name')
    op.add_column('cactus_library', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('cactus_library', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cactus_library', type_='foreignkey')
    op.create_foreign_key(op.f('cactus_library_created_by_fkey'), 'cactus_library', 'users', ['created_by'], ['id'])
    op.drop_index('ix_cactus_library_type', table_name='cactus_library')
    op.drop_index('ix_cactus_library_recommended', table_name='cactus_library')
    op.drop_index('ix_cactus_library_completion', table_name='cactus_library')
    op.drop_index('ix_cactus_library_added_by', table_name='cactus_library')
    op.create_index(op.f('ix_cactus_library_updated_at'), 'cactus_library', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cactus_library_title'), 'cactus_library', ['title'], unique=False)
    op.create_index(op.f('ix_cactus_library_is_completed'), 'cactus_library', ['is_completed'], unique=False)
    op.create_index(op.f('ix_cactus_library_created_by'), 'cactus_library', ['created_by'], unique=False)
    op.create_index(op.f('ix_cactus_library_created_at'), 'cactus_library', ['created_at'], unique=False)
    op.create_index(op.f('ix_cactus_library_content_type_rating'), 'cactus_library', ['content_type', 'rating'], unique=False)
    op.create_index(op.f('ix_cactus_library_content_type'), 'cactus_library', ['content_type'], unique=False)
    op.create_index(op.f('ix_cactus_library_author'), 'cactus_library', ['author'], unique=False)
    op.alter_column('cactus_library', 'content_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('cactus_library', 'added_by')
    op.drop_column('cactus_library', 'notes')
    op.drop_column('cactus_library', 'completion_status')
    op.drop_column('cactus_library', 'is_recommended')
    op.drop_column('cactus_library', 'duration_minutes')
    op.drop_column('cactus_library', 'isbn')
    op.create_index(op.f('ix_cactus_ideas_updated_at'), 'cactus_ideas', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cactus_ideas_title'), 'cactus_ideas', ['title'], unique=False)
    op.create_index(op.f('ix_cactus_ideas_status_priority'), 'cactus_ideas', ['status', 'priority'], unique=False)
    op.alter_column('cactus_ideas', 'due_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('cactus_ideas', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('cactus_ideas', 'assigned_to')
    op.drop_column('cactus_ideas', 'estimated_hours')
    op.add_column('cactus_external_links', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cactus_external_links', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('ix_cactus_links_role', table_name='cactus_external_links')
    op.drop_index('ix_cactus_links_order', table_name='cactus_external_links')
    op.drop_index('ix_cactus_links_created_by', table_name='cactus_external_links')
    op.drop_index('ix_cactus_links_active', table_name='cactus_external_links')
    op.create_index(op.f('ix_cactus_external_links_updated_at'), 'cactus_external_links', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cactus_external_links_title'), 'cactus_external_links', ['title'], unique=False)
    op.create_index(op.f('ix_cactus_external_links_order_index'), 'cactus_external_links', ['order_index'], unique=False)
    op.create_index(op.f('ix_cactus_external_links_is_active'), 'cactus_external_links', ['is_active'], unique=False)
    op.create_index(op.f('ix_cactus_external_links_created_by'), 'cactus_external_links', ['created_by'], unique=False)
    op.create_index(op.f('ix_cactus_external_links_created_at'), 'cactus_external_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_cactus_external_links_category_order'), 'cactus_external_links', ['category', 'order_index'], unique=False)
    op.create_index(op.f('ix_cactus_external_links_category'), 'cactus_external_links', ['category'], unique=False)
    op.drop_column('cactus_external_links', 'required_role')
    op.drop_column('cactus_external_links', 'color')
    op.drop_column('cactus_external_links', 'name')
    op.add_column('cactus_content_matrix', sa.Column('estimated_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cactus_content_matrix', sa.Column('content_brief', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_cactus_content_published', table_name='cactus_content_matrix')
    op.drop_index('ix_cactus_content_publish_date', table_name='cactus_content_matrix')
    op.drop_index('ix_cactus_content_created_by', table_name='cactus_content_matrix')
    op.drop_index('ix_cactus_content_category', table_name='cactus_content_matrix')
    op.create_index(op.f('ix_cactus_content_matrix_updated_at'), 'cactus_content_matrix', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cactus_content_matrix_title'), 'cactus_content_matrix', ['title'], unique=False)
    op.create_index(op.f('ix_cactus_content_matrix_created_by'), 'cactus_content_matrix', ['created_by'], unique=False)
    op.create_index(op.f('ix_cactus_content_matrix_created_at'), 'cactus_content_matrix', ['created_at'], unique=False)
    op.create_index(op.f('ix_cactus_content_matrix_category'), 'cactus_content_matrix', ['category'], unique=False)
    op.alter_column('cactus_content_matrix', 'category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('cactus_content_matrix', 'publish_date')
    op.drop_column('cactus_content_matrix', 'is_published')
    op.drop_column('cactus_content_matrix', 'content_url')
    op.drop_column('cactus_content_matrix', 'description')
    op.drop_index('ix_webauthn_credentials_user_id', table_name='webauthn_credentials')
    op.drop_index('ix_webauthn_credentials_last_used_at', table_name='webauthn_credentials')
    op.drop_index('ix_webauthn_credentials_credential_id', table_name='webauthn_credentials')
    op.drop_index('ix_webauthn_credentials_created_at', table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index('ix_email_tokens_user_id', table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_token'), table_name='email_tokens')
    op.drop_index('ix_email_tokens_expires_at', table_name='email_tokens')
    op.drop_table('email_tokens')
    # ### end Alembic commands ###
