"""add_savings_capacity_to_clients

Revision ID: 8fd147a36583
Revises: 4b39e0ac02f2
Create Date: 2025-07-25 00:31:30.687173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd147a36583'
down_revision: Union[str, None] = '4b39e0ac02f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('savings_capacity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'savings_capacity')
    # ### end Alembic commands ###
