name: Frontend CI

on:
  pull_request:
    paths:
      - 'cactus-wealth-frontend/**'
      - '.github/workflows/frontend-tests.yml'
  push:
    branches:
      - main
    paths:
      - 'cactus-wealth-frontend/**'
      - '.github/workflows/frontend-tests.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cactus-wealth-frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: cactus-wealth-frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --fund=false

      - name: Lint
        run: npm run lint:ci

      - name: Type check
        run: npm run type-check

      - name: Run tests (PR, non-strict)
        if: github.event_name == 'pull_request'
        run: npm run test:ci

      - name: Run tests (main, strict logs)
        if: github.event_name == 'push'
        run: npm run test:ci:strict


